project:
  type: website
  output-dir: docs

website:
  title: "Evaluating the Effectiveness of NYC Subway Accessibility for Schools"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true



